### get all payment

GET http://localhost:3000/payment

### get all payment with search params
GET http://localhost:3000/payment?q=ses

### detail Payment
GET http://localhost:3000/payment/2025021

### generate url register
GET http://localhost:3000/payment/generate/2025021

### add payment return url register
POST http://localhost:3000/payment/
Content-Type: application/json

{
    "nama":"Sesko",
    "noHp": "0812828918299",
    "anualFee":5000000,
    "tuitionFee":300000,
    "registrationFee":100000,
    "uniformFee":50000,
    "paymentPhoto":"nhfkahfkhnae,fnjkeanbkhfaskfhuae"
}

### add payment instalment
POST http://localhost:3000/payment/
Content-Type: application/json

{
    "nama":"Benjamin",
    "noHp": "0812828918299",
    "anualFee":0,
    "tuitionFee":0,
    "registrationFee":0,
    "uniformFee":0,
    "paymentPhoto":"nhfkahfkhnae,fnjkeanbkhfaskfhuae",
    "isInstalment":true,
    "paymentFee":1000000
}

### add instalment
POST http://localhost:3000/payment/instalment/4qAaBgNALtY1kbi5__wJp
Content-Type: application/json

{
   "paymentFee":1000000
}

### edit payment
PUT http://localhost:3000/payment/2025021
Content-Type: application/json

{
    "isInstalment":false,
    "anualFee":5000000,
    "tuitionFee":500000,
    "registrationFee":500000,
    "uniformFee":50000
}